=== tboox/tbox/src/demo/linux_x86/test/xml/Invoice/Invoice.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Invoice (Header,Item+)>
<!ELEMENT Header (Date,BillTo)>
<!ATTLIST Header
 invoiceNumber CDATA #REQUIRED
>
<!ELEMENT Item (description*)>
<!ATTLIST Item
 price CDATA #REQUIRED
 discount (promotion | regular) "regular"
>
<!ELEMENT Date ((Month,Day,Year)|(Day,Month,Year))>
<!ELEMENT BillTo (Address)>
<!ATTLIST BillTo
 custNumber ID #REQUIRED
 name CDATA #IMPLIED
 phone CDATA #IMPLIED
>
<!ELEMENT description (#PCDATA)>
<!ELEMENT Address (street1,street2?,city,(state|province),zip,country?)>
<!ELEMENT street1 (#PCDATA)>
<!ELEMENT street2 (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT province (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT Month (#PCDATA)>
<!ELEMENT Day (#PCDATA)>
<!ELEMENT Year (#PCDATA)>

=== tboox/tbox/src/demo/linux_x86/test/xml/Invoice/Invoice.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Invoice PUBLIC "InvoiceId" "Invoice.dtd" >
<Invoice>
  <Header invoiceNumber="12345">
    <Date>
      <Month>July</Month>
      <Day>15</Day>
      <Year>2001</Year>
    </Date>
    <BillTo custNumber="X5739" name="Milton McGoo" phone="416-448-4414">
      <Address>
        <street1>IBM</street1>
        <street2>1150 Eglinton Ave East</street2>
        <city>Toronto</city>
        <state>Ontario</state>
        <zip>M3C 1H7</zip>
        <country>Canada</country>
      </Address>
    </BillTo>
  </Header>
  <Item discount="promotion" price="57">
    <description>high speed 3D graphics card</description>
  </Item>
</Invoice>
